let userScorepara = document.querySelector("#user-score");
let userScore = 0;    // initial count for users score 
let compScorepara = document.querySelector("#comp-score");
let compScore = 0;    // initial count for computers score

const choices = document.querySelectorAll(".btn");
let message  = document.querySelector("#result");

// Taking User Choise
choices.forEach((btn)=>{

    btn.addEventListener("click",()=>{                 // Tracking user click 
        const userChoice =  btn.getAttribute("id");    // accesing all the buttons 
        playGame(userChoice);   // passsig user choice to check with the computer choice 

    });

});

//Generating computer's choice
let compChoice = ()=>{

    //storing values of rock , paper and scissor inside an array 
    let gameArr = ["Rock","Paper","Scissor"];
    let rndidx = Math.floor(Math.random()*3);  // Math.floor removes decimal points of numbers generated by Math.random  

    return gameArr[rndidx];           // It will return random index of gameArr array could be rock paper or scissors

};

// Getting choices of both the user and the computer and comparing both 
const playGame = (userChoice)=>{
    console.log("User chose",userChoice)

    //computer choice
   let genChoice =  compChoice();
   console.log("Computer chose",genChoice);

   // DRAW condition
   if(userChoice === genChoice){  // condition for checking draw condition 
        draw();
   }else {
        let userWin = true;      // To check if user is winning or not take a variable and set it TRUE

 // if userChoice is rock and comp chose paper then set userWin to false or if scissor then set true again
        if (userChoice ==="Rock"){
            //Comp had paper or scissor
           userWin =  genChoice === "Paper" ? false:true;       // false indicating user lost
        } else if(userChoice === "Paper") {
            //rock or scissor
            userWin = genChoice === "Scissor" ? false:true;    
        }else{
            // rock or paper
            userWin = genChoice === "Rock" ? false:true ;

        }

        showWinner(userWin);
   }
};

// Function to check draw condition 
const draw = ()=>{
        console.log("Its a Draw");
        message.innerText = "Its a Draw";
        message.style.backgroundColor = "Yellow";
};


// Function displaying Winner
const showWinner=(userWin)=>{
 
    if(userWin){                       // if userWin is true 
        console.log("You won");
        message.innerText = "You Won !!";
        message.style.backgroundColor = "lime";
        userScore++;   // values will be updated 
        userScorepara.innerText = userScore;     // new values will be printed according to winner 

    }else{
        console.log("You lost");
        message.innerText = "You Lost";
        message.style.backgroundColor = "crimson";
        compScore++;
        compScorepara.innerText = compScore;
    }

};